### ISSUE TITLE
[Bug]: fps drop with statues

### ISSUE THREAD

**Issue by MrArofun** [DarkPacks/SkyFactory-One#101]
### General Info

- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

Java 8

### Modpack Launcher Used

Launcher

### Memory Allocated

5 GB

### Minecraft World Environment

Server

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

When you place a statue from Statues Mod fps drops instantly. Noticed it, when placed my own one.

**Comment by ivxvm** [comment]
In my experience, there are some FPS issues only with player statues, but not mob statues. It seems player statues perform some weird networking stuff (maybe even web requests?) every time you look at them, because when I lost internet connection every time I accidentaly looked at my own statue the game would hang for like 30 seconds suggesting it was waiting for web response and timed out.

**Comment by Darkosto** [comment]
This is actually an issue with the base game. It happens a lot more often than you may realize. This is a fix that vanilla made in the 1.17 release and we have to live with until we get to that version. The devs are unable to make this fix so unfortunately, this is something we can't change.

In the meantime, I would suggest being cognizant of the blocks and items you place down in the world. For example, item frames will also drop your FPS.
