### ISSUE TITLE
[Suggestion]: Uncrafting Grinder from cyclic 

### ISSUE THREAD

**Issue by BajanLuke** [DarkPacks/SkyFactory-One#127]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

It would be a cool addition if the Uncrafting Grinder from cyclic could uncraft storage disks from Refined Storage

**Comment by Darkosto** [comment]
I'm not sure if this is a recipe I want to allow automation with. I just went back to all the AE, AE2, and Refined storage versions I've used since 1.6.4 and none of them allowed a recipe to uncraft the disks. My thought is, the mods have done this purposefully so players do not accidently uncraft a drive full of important items. Knowing players, if I added an easy, automatable way to separate the storage disk and housing, users will end up deleting items and blame the pack.

Having said that, you can shift-right click a drive and it should separate the housing and storage parts. It's not ideal, but at least you can reuses the parts that way.
