### ISSUE TITLE
[Suggestion]: Add Quark

### ISSUE THREAD

**Issue by Insane96** [DarkPacks/SkyFactory-One#151]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

While Quark is an all around Vanilla+ mod, there are some really useful feature that would make the SkyBlock life better, such as reacharound placing which let you place blocks below a block you're standing on even horizontally (like Bedrock edition). Lock rotation is another feature I personally love to build and makes it easier to build with multi-rotation blocks. Some features would need to be disabled as overlap with other mods (such as right-click harvesting). Other useful features are multiple new blocks and decorations and [Crabs](https://twitter.com/Vazkii/status/1150541341438464000).

**Comment by Darkosto** [comment]
Quark is not a mod I'd like to add to this modpack: It has an extremely large feature set that is outside the scope of this modpack. This pack is not a generic skyblock pack, it is a remake of the original SkyFactory. The new blocks, entities, and decorations you speak of would add much more than the original modpack had. The point is not to add so many new features and mechanics that it becomes a new SkyFactory modpack (or else I would have made a SkyFactory 5). We want to embrace new features in the base game and tried to keep many features as close to SF1 as possible. I find Quark to be over the line on how much new content we add.

The reach-around feature you asked for exists already in Construction wands while other mechanics exist in mods like Cyclic. 

Aside from that, I do not find working with the Quark config to be enjoyable. We have fought with the mod in the past, especially during updates that will update the config and reenable features we do not want. All of us have limited time and spending time working with a mod that has an enormous config like Quark is requires too many resources. I'm not really a fan of having to add a mod and spend time disabling many of the features to a much smaller number since the majority of this mod does not fit into this pack.
