### ISSUE TITLE
[Bug]: no way to get zinc

### ISSUE THREAD

**Issue by Litt1eThief** [DarkPacks/SkyFactory-One#166]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.4

### Java version

17.0.1

### Modpack Launcher Used

curseforge launcher 

### Memory Allocated

8

### Minecraft World Environment

Single Player

### Misc Client Info

- [X] Optifine Installed
- [X] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

i did add the create mod off of curseforge to the mod pack. when looking in the just enough items it show the zinc ore piece which is gotten from the sieve but it does not show what block to use and ive tried every block and still have not gotten it.

**Comment by Darkosto** [comment]
This is a not bug with the modpack since you have added the mod yourself. The pack is setup to use the mods we ship and does not support adding new mods. 

You can go ahead and add this yourself by creating a recipe for it but I will not be adding support for this since I do not include Create in the pack.
