### ISSUE TITLE
[Bug]: Crash on pack launch

### ISSUE THREAD

**Issue by Tanden22** [DarkPacks/SkyFactory-One#173]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.4

### Java version

Java 8 update 333

### Modpack Launcher Used

MultiMC, downloaded with ATLauncher option

### Memory Allocated

8 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

During the "Deep Scan" portion of startup, the game crashes with a "java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V" error. The only similar issue I managed to find was #164. Crash report is linked below.

(Oddly enough, I was able to load into the pack and even make a new world while using Java 17, but I had the same problem as #54 and #83.)

### Additional Information

https://pastebin.com/nLsg9xQm

**Comment by sam-kirby** [comment]
A security vulnerability in Java was discovered last year, and the fix for it broke modlauncher (one of Forge's components). This fix was applied to Java 17, 11 and 8 so this implies you have an outdated version of Java 17 installed.

The fix is to update the pack to 1.0.5, which contains an updated version of Forge that works with new versions of Java. This issue is being closed as the issue is already resolved.
