### ISSUE TITLE
[Bug]: Players respawn in the void

### ISSUE THREAD

**Issue by TheDeviantCrafter** [DarkPacks/SkyFactory-One#54]
### General Info

- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Modpack version

1.0.0

### Java version

Java 8 update 301

### Modpack Launcher Used

GDLauncher

### Memory Allocated

4 GB

### Minecraft World Environment

Server

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Server Java Version

Java 8 update 301

### Server Operating System

Windows 10

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

When players die in multiplayer, they respawn about 20 blocks away from 0,0 where the tree spawns. This sends them into a death loop as it is impossible to reach the island in that time.

### Additional Information

As a temporary workaround, changing the spawn point with /setworldspawn can fix the issue. Issue #53 means that this will have to be done after every server restart (or via repeating command block).

**Comment by klugemonkey** [comment]
Seems like when topography starts for first time, it adds custom dimensions to the WorldGenSettings on the server.  

But for some reason the level.dat is not saved with this information.  If the player dies shortly after spawning on the tree (aka. /kill), then respawns on the tree, and disconnects, then is stopped, the level.dat file does not contain the modified WorldGenSettings.  

When the server is started, something is trying to be read that is non-existent in the level.dat and cascades into an error about null in plains biome.   

Then when the player joins again, they are in the wrong location, possibly since the seed that was in memory is not what was in the original level.dat.

However, if you followed the same process and did /save-all after respawning and before rebooting, everything works as expected since the level data in memory is saved to file first.  Or if the server has time to automatically save before the first reboot, this issue might not occur.

So, perhaps this is an issue of the level information not being saved from memory to the level.dat file after being changed by the topography mod.  

This is probably all the same issue #53, #54, #60
