### ISSUE TITLE
[Suggestion]: Maybe change the droprate on cobalt pieces and Netherite scrap

### ISSUE THREAD

**Issue by SgtMorrigahnGaming** [DarkPacks/SkyFactory-One#96]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Maybe it's just me, and my usual luck, but after sieving 9 stacks of crushed Netherrack to get Netherite scrap, I've gotten 1 Cobalt piece and 0 scrap. I can see it's supposed to be 0.8% chance of scrap, but maybe it's a tad to low??
It's been a long time getting the dust, to get redstone, getting lava, making all that netherrack, ending up with nothing so far...

I know things change when you get the 2 scrap needed to make stonefactory .. but to get those 2?!?!? :D :D :D

Using the latest version of Skyfactory One, 1.0.2

**Comment by VeryGoodDev** [comment]
Just chiming in to note that I went through about 12 stacks of crushed netherrack with no scraps, but the second I made a Mystical Agriculture nether essence farm to mass produce netherrack for crushing/sifting, I got two scraps from the first stack I sifted, and 5 scraps total from 9 stacks sifted. RNG is some weird stuff, but for anyone struggling with this, I would definitely recommend considering nether essence in Mystical Agriculture as an alternative to getting the scraps you need before you have any better ways to get it. It does take a little initial setup, but it's _much_ more sustainable than the redstone/lava method (and you can use the essence to craft other nether blocks, so it still can be useful for other things as well)

**Comment by Darkosto** [comment]
I'm going to close this because I do not feel altering these drop rates need to be increased. I've gone through and tested out these drop rates and they are in fact working as stated, so there is no bug with how often they should drop. 

Having said that, the overall point of this modpack is automation. If I were to increase the drop rate because people sieving by hand aren't getting as many as they think they should then it will overflow when other players have automated it. Both Netherite and Cobalt are "late game" materials and extremely powerful. I don't see value in increases their drop rates and effecting the overall progression. 

My suggestion would be to setup a method that allows to automate the creation of these materials so you can passively generate them. I've spent many hours of testing and in each of my survival worlds I was able to get plenty of these materials over time. I'm sure that's not what you wanted to hear. Thank you for the report none the less!
